### ISSUE TITLE
[BUG] Phyn Smart Water Sensor expose incorrect home assistant sensors

### ISSUE THREAD

**Issue by Hedda** [jordanruthe/homeassistant-phyn#14]
Copy of bug report from @snairolf to upstream https://github.com/MizterB/homeassistant-phyn/issues/7 in regards to the "[Phyn Smart Water Sensor](https://phyn.com/products/smart-water-sensor)" leak sensor type product which also features `air temperature` and `air humidity` sensors in addition to the water leak detector sensor -> https://phyn.com/products/smart-water-sensor

> The smart sensors seem to expose 'daily water usage', 'average water flow rate', 'average water pressuer', 'average water temperature', whereas in the app 'air temperature' and 'air humidity' and 'detected leak' are shown.

> Here is the dump for a sensor:
> 
> ```
> {'auto_shutoff_eligible': 0,
>   'auto_shutoff_enable': True,
>   'battery_level': {'ts': 1693731332897, 'v': 75},
>   'created_ts': 1654705582265,
>   'device_id': 'REMOVED',
>   'fw_version': '10803000',
>   'humidity': {'ts': 1693731329, 'v': 61},
>   'hw_version': '0',
>   'name': 'Kitchen Sink',
>   'network_name': 'REMOVED',
>   'online_status': {'ts': 1684124769281, 'v': 'online'},
>   'partner': 'phyn',
>   'product_code': 'PW1',
>   'sd_status': {'ts': 1693731332897, 'v': 'G'},
>   'serial_number': 'REMOVED',
>   'signal_strength': 73,
>   'temperature': {'ts': 1693731329, 'v': 82},
>   'timezone': 'REMOVED',
>   'users': ['REMOVED']}
> ```

**Comment by jordanruthe** [comment]
This should be fixed as of v2024.1.3 or c40718a.
