### ISSUE TITLE
[REQUEST] Water flow rate class update from fork by timbba80

### ISSUE THREAD

**Issue by Hedda** [jordanruthe/homeassistant-phyn#15]
Please look if need merge "Water flow rate class update" patches from pull request from fork by @timbba80 here -> https://github.com/timbba80/homeassistant-phyn/pull/1

PS: @timbba80 also have merged a Finish (FI) language translation to his fork as part of that pull request. See:

* https://github.com/timbba80/homeassistant-phyn

**Comment by timbba80** [comment]
Please see pull request #18, should work.

**Comment by jordanruthe** [comment]
I'm going to close this since the PR should have addressed it. I'm open to discussion if I got it wrong
