### ISSUE TITLE
[REQUEST] Make use of the new valve entity, device class, and valve control services?

### ISSUE THREAD

**Issue by Hedda** [jordanruthe/homeassistant-phyn#19]
Please consider implementing the use of the new `valve` entity to present shutoff valves as OPEN/CLOSE "valve" instead of as an ON/OFF "switch":

https://www.home-assistant.io/integrations/valve/

https://www.home-assistant.io/integrations/valve/#device-class

https://www.home-assistant.io/integrations/valve/#valve-control-services

https://www.home-assistant.io/integrations/valve/#service-valveset_position

This device type in Home Assistant is meant to provide a clearer defined interface to control valves such as water, gas, or air valves.

This might be a breaking change but not a huge change and it could be worth it to have a more properly suited device class.

If supported in then users can at least manually modify any `switch` device type that controls a valve device type and device class so it is presented as a valve by changing it to `valve` in the customize section of the UI or device config in `configuration.yaml`:

https://www.home-assistant.io/docs/configuration/customizing-devices/

Initially this new valve entity so far support the following device classes:

- _**None**: Generic valve. This is the default and doesn’t need to be set._
- _**water**: Valve that controls the flow of water through a system._
- _**gas**: Valve that controls the flow of gas through a system._

Anyway, this new `valve` entity, device class, and valve control services for use were added in Home Assistant 2024.1

https://www.home-assistant.io/blog/2024/01/03/release-20241/#new-entity-type-valve

Added by [cibernox](https://github.com/cibernox) as entity type and device type for valves, which can be used by integrations to expose different type of valves.

### _New entity type: Valve_

**_A brand new entity type has been added to Home Assistant: Valve!_**

**_Integrations can use this entity type to expose valves, such as a valve on a radiator, pool, sprinkler system, and main house gas or water line._**

![image](https://github.com/jordanruthe/homeassistant-phyn/assets/6320001/905f206a-bbc8-44f2-a2df-e86992d1916d)

**_Currently, the [Shelly integration](https://www.home-assistant.io/integrations/shelly) supports it and now provides a valve entity for the Valve addon for [Shelly Gas AddOn Manipulator](https://www.shelly.com/en-us/products/shop/shelly-gas-add-on-manipulator-us). Additionally, support for it has been added to [MQTT](https://www.home-assistant.io/blog/2024/01/03/release-20241/integrations/valve.mqtt), and the valve entities also work with Amazon Alexa and Google Assistant._**

_**Tip: Do you have a switch entity that controls a valve? You can now change the entity type to valve in the entity settings.**_

**Comment by Hedda** [comment]
> Currently, the [Shelly integration](https://www.home-assistant.io/integrations/shelly) supports it and now provides a valve entity for the Valve addon for [Shelly Gas AddOn Manipulator](https://www.shelly.com/en-us/products/shop/shelly-gas-add-on-manipulator-us). Additionally, support for it has been added to [MQTT](https://www.home-assistant.io/blog/2024/01/03/release-20241/integrations/valve.mqtt), and the valve entities also work with Amazon Alexa and Google Assistant.

By the way, since the blog post other integrations have implemented it to, including allowing toggle of valve via Google Assistant:

https://github.com/home-assistant/core/pulls?q=is%3Apr+valve+

FYI, for reference please also see "water" for other integrations that use it (or should use this as well as other similar sensors):

https://www.home-assistant.io/docs/energy/water/

**_We have the following integrations available for existing products that can provide information about water usage:_**

* [Flo](https://www.home-assistant.io/integrations/flo)
* [Flume](https://www.home-assistant.io/integrations/flume)
* [HomeWizard Energy](https://www.home-assistant.io/integrations/homewizard)
* [P1 Monitor](https://www.home-assistant.io/integrations/p1_monitor)
* [StreamLabs](https://www.home-assistant.io/integrations/streamlabswater)
* [Suez Water](https://www.home-assistant.io/integrations/suez_water)

**Comment by jordanruthe** [comment]
This started using the valve entity with c3107d6
