### ISSUE TITLE
Metric units or better yet, possibility to select wanted units.

### ISSUE THREAD

**Issue by Din-BH** [jordanruthe/homeassistant-phyn#21]
HomeAssistant converts US customary units to Metric units automatically in many cases. Unfortunately not all, and with the new brilliant capabilities to see real time values such as real time flow, this becomes more visible. The flow is set to gpm - Gallons per minute. In a metric setup, this should be converted to "l/min" - Liters per minute - (or "lpm" depending on source).

Even better if it would be possible to set on your own to use "bar" instead of "kPa", if that feels like a more natural unit for pressure in water systems at least to me...

Of course both of these can be circumvented through helpers or templates, but if there is a way to make at least the first happen automatically to honor the system settings, then that would at least clearly be useful.

**Comment by jordanruthe** [comment]
Pr #18 fixes this. It should be completed soon

**Comment by Din-BH** [comment]
Perfect, thanks!

**Comment by Din-BH** [comment]
Latest release indeed fixes the gpm vs l/m topic. Thanks for lightning fast fixing!

Ability to select "bar" instead of "kPa" - both obviously technically correct - would still be nice to have. Therefore this is at least no longer a bug, but rather a feature request.

**Comment by jordanruthe** [comment]
I'm not sure what you mean, those are supported units in home assistant and you should be able to choose bar, kPa, etc. 
![Screenshot_20240128-125236](https://github.com/jordanruthe/homeassistant-phyn/assets/31575189/fbfe537e-e915-4844-ab1f-e1ed8ccfdc30)

**Comment by Din-BH** [comment]
Ahem.. Apperently I have missed a core feature. I stand corrected. It works indeed just as you describe. Thank you very much, and sorry for the confusion!
