### ISSUE TITLE
[aiophyn.mqtt] MQTT Connection Error

### ISSUE THREAD

**Issue by snairolf** [jordanruthe/homeassistant-phyn#22]
I keep getting connection errors and then the sensors don't update. Reloading the integration fixes it, but sometimes only for a few minutes. This is on v2024.1.3

Happy to help debug.

**Comment by jordanruthe** [comment]
If you can post the debug log, that would be extremely helpful

**Comment by snairolf** [comment]
Currently not reproducable anymore.

**Comment by snairolf** [comment]
Currently not reproducable anymore.
