### ISSUE TITLE
Repository URL wrong

### ISSUE THREAD

**Issue by shettich** [jordanruthe/homeassistant-phyn#25]
I have not installed yet, but I'm guessing the URL for the repository in the README is wrong, and it should be this repo?

**Comment by Hedda** [comment]
Yes see -> https://github.com/jordanruthe/homeassistant-phyn/pull/11

**Comment by Hedda** [comment]
@jordanruthe readme in repo now has correct URL but need another new release so latest release get correct URL too

https://github.com/jordanruthe/homeassistant-phyn/releases

**Comment by Hedda** [comment]
This can be closed now with v2024.10.0 -> https://github.com/jordanruthe/homeassistant-phyn/releases/tag/v2024.10.0

That included corrct URL in README.md - > https://github.com/jordanruthe/homeassistant-phyn/blob/main/README.md
