### ISSUE TITLE
Flow Rate Sensor warning message in system logs

### ISSUE THREAD

**Issue by kshepard339** [jordanruthe/homeassistant-phyn#28]
The following warning is appearing in system logs:

Entity sensor.phyn_pp1_current_water_flow_rate (<class 'custom_components.phyn.devices.pp.PhynCurrentFlowRateSensor'>) is using state class 'measurement' which is impossible considering device class ('water') it is using; expected None or one of 'total_increasing', 'total'; Please update your configuration if your entity is manually configured, otherwise report it to the author of the 'phyn' custom integration

The warning is resolved if class PhynCurrentFlowRateSensor (in pp.py) is updated from:
_attr_device_class = SensorDeviceClass.WATER to:
_attr_device_class = SensorDeviceClass.VOLUME_FLOW_RATE

**Comment by kshepard339** [comment]
There is one more warning which is related to gallons per minute. HA expects the unit to be expressed as gal/min instead of gpm.

Entity sensor.phyn_pp1_current_water_flow_rate (<class 'custom_components.phyn.devices.pp.PhynCurrentFlowRateSensor'>) is using native unit of measurement 'gpm' which is not a valid unit for the device class ('volume_flow_rate') it is using; expected one of ['m³/h', 'L/min', 'ft³/min', 'gal/min']; Please update your configuration if your entity is manually configured, otherwise report it to the author of the 'phyn' custom integration

**Comment by jordanruthe** [comment]
Thanks, looks like this was added in HA 2024.2.3. I'll update the sensors shortly.
