### ISSUE TITLE
[Request] Real time data for flow, pressure and temp sensors

### ISSUE THREAD

**Issue by Madbeefer** [jordanruthe/homeassistant-phyn#30]
Is there a way to pull real time data for flow, pressure and temp instead of an average?

**Comment by jordanruthe** [comment]
The integration already pulls real time flow, pressure, and temperature data.

**Comment by Madbeefer** [comment]
Oh, maybe I did something wrong, I only have the sensors that have averages for flow pressure and temp.

**Comment by jordanruthe** [comment]
What is the model of your device? Is it a phyn classic device or a phyn plus?

**Comment by Madbeefer** [comment]
It is a phyn plus

**Comment by Hedda** [comment]
@Madbeefer Which exact GitHub repository URL did you use when installing?

@jordanruthe asking as your README.md file still points to the wrong repo:

* https://github.com/jordanruthe/homeassistant-phyn/pull/11

* https://github.com/jordanruthe/homeassistant-phyn/issues/25

**Comment by Madbeefer** [comment]
Apparently I let the readme led me astray and I was using the one it was pointed to, switch to this one and those sensors are there. Thanks

**Comment by Hedda** [comment]
This too can be closed now with v2024.10.0 -> https://github.com/jordanruthe/homeassistant-phyn/releases/tag/v2024.10.0

That included correct URL in README.md - > https://github.com/jordanruthe/homeassistant-phyn/blob/main/README.md
