### ISSUE TITLE
Add this Phyn integration to HACS (Home Assistant Community Store)?

### ISSUE THREAD

**Issue by Hedda** [jordanruthe/homeassistant-phyn#32]
Please consider adding/contributing this Phyn integration to HACS (Home Assistant Community Store):

- https://hacs.xyz
  -  https://hacs.xyz/docs/publish/

That is, it would be awesome if this repo could be included as a default repository in HACS so it will be much easier for users to find this:

https://hacs.xyz/docs/publish/include/

I think this request is more relevant now that HACS  (Home Assistant Community Store) itself has reached v2.0 which makes it easier:

https://www.home-assistant.io/blog/2024/08/21/hacs-the-best-way-to-share-community-made-projects/

**Comment by jordanruthe** [comment]
I've submitted it as a PR. https://github.com/hacs/default/pull/2755

**Comment by jordanruthe** [comment]
It should be added as of today.
